### ISSUE TITLE
version-2 

### ISSUE THREAD

**Issue by tobiasrother** [visualengineers/cobro-backend#11]
As I am worked at the logging #5, I decided to rewrite the entiry App.
Now it has a proper entry point and variable logging system, which will be finished shortly.
 
The data is now seperated form the app and the routes. 
And also I think it'll be easier to set up at Netlify now.

**Comment by dkammer** [comment]
This looks good. I think @ChevapGG should check the pattern visualizer against this new version. If everything works, please create pull request for master branch @tobiasrother

**Comment by ChevapGG** [comment]
@dkammer I have tested version-2 of the back-end with my current front-end and found no conflicts. 
Feel free to create the pull request for the master branch @tobiasrother

**Comment by tobiasrother** [comment]
#12 Version-2 is now live on the maser branch.
