### ISSUE TITLE
Deliver Block JSON with more information

### ISSUE THREAD

**Issue by dkammer** [visualengineers/cobro-backend#3]
- [x] Add SVG code to JSON reply of server
- [x] Standard route blocks/:id returns meta information and SVG object
- [x] Enhance route to blocks with switch (*svg* (only svg file), *plain* (only meta information without SVG, *png* for PNG image)

**Comment by tobiasrother** [comment]
The svg data can only be imported encoded into JSON. Decoding works with the function [decodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI)

The request /blocks/:id/:format with format: all/plain/svg/png now response the requested data. The svg request response with a decoded svg String. No need to decode.

**Comment by dkammer** [comment]
Add information about decoding SVG data from JSON response in documentation, then close issue.
